In [232]:
import pandas as pd
import numpy as np

In [176]:
data=pd.read_csv(r"C:\Users\PIYUSH\Desktop\train.csv")

In [177]:
data=pd.DataFrame(data)

In [178]:
data.shape

(43266, 9)

In [179]:
data.head()

Complaint-ID Date-received         Transaction-Type  \
0         Tr-1    11/11/2015                 Mortgage   
1         Tr-2      7/7/2015         Credit reporting   
2         Tr-3      5/7/2015  Bank account or service   
3         Tr-4    11/12/2016          Debt collection   
4         Tr-5     9/29/2016              Credit card   

                           Complaint-reason  \
0  Loan servicing, payments, escrow account   
1    Incorrect information on credit report   
2                 Using a debit or ATM card   
3     Cont'd attempts collect debt not owed   
4                            Payoff process   

                                    Company-response Date-sent-to-company  \
0                                                NaN           11/11/2015   
1   Company chooses not to provide a public response             7/7/2015   
2                                                NaN             5/7/2015   
3  Company believes it acted appropriately as aut...           11/12/2016   
4  Company has responded to the consumer and the ...            9/29/2016   

                  Complaint-Status Consumer-disputes  \
0          Closed with explanation               Yes   
1  Closed with non-monetary relief                No   
2          Closed with explanation                No   
3          Closed with explanation                No   
4          Closed with explanation                No   

                          Consumer-complaint-summary  
0  Seterus, Inc a déposé un faux rapport auprès d...  
1  XX / XX / XXXX La requête en faillite n ° XXXX...  
2  El XXXX / XXXX / 15, estaba preparando el vuel...  
3  The loan was paid in XXXX XXXX. In XXXX, 4 yea...  
4  J'ai obtenu un compte de crédit de soins pour ...

In [180]:
data.isnull().sum()

Complaint-ID                      0
Date-received                     0
Transaction-Type                  0
Complaint-reason                  0
Company-response              22506
Date-sent-to-company              0
Complaint-Status                  0
Consumer-disputes              7698
Consumer-complaint-summary        0
dtype: int64

In [181]:
data["Company-response"].unique()

array([nan, 'Company chooses not to provide a public response',
       'Company believes it acted appropriately as authorized by contract or law',
       'Company has responded to the consumer and the CFPB and chooses not to provide a public response',
       'Company disputes the facts presented in the complaint',
       'Company believes complaint is the result of an isolated error',
       'Company believes the complaint is the result of a misunderstanding',
       'Company believes complaint represents an opportunity for improvement to better serve consumers',
       'Company believes complaint caused principally by actions of third party outside the control or direction of the company',
       "Company can't verify or dispute the facts in the complaint",
       'Company believes complaint relates to a discontinued policy or procedure'],
      dtype=object)

In [182]:
data["Complaint-Status"].unique()

array(['Closed with explanation', 'Closed with non-monetary relief',
       'Closed', 'Closed with monetary relief', 'Untimely response'],
      dtype=object)

In [183]:
ls=[]
count=-1
for i in data["Complaint-Status"]:
    count+=1
    if i == "Closed with non-monetary relief":
        ls.append(count)


In [184]:
len(ls)

5018

In [185]:

c=0
s="nan"
rep_s="Company has responded to the consumer and the CFPB and chooses not to provide a public response"
for i in ls:
    if s == str(data["Company-response"].iloc[i]):
        data["Company-response"].iloc[i]=rep_s


In [186]:
data["Company-response"].iloc[6054]

'Company has responded to the consumer and the CFPB and chooses not to provide a public response'

## nans replaced for Closed with non-monetary relief

In [187]:
ls=[]
count=-1
for i in data["Complaint-Status"]:
    count+=1
    if i == "Closed with explanation":
        ls.append(count)


In [188]:
len(ls)

34300

In [189]:
ls1=[]
count=0
for i in ls:
    ls1.append(data["Company-response"].iloc[i])
for i in ls1:
    if "nan"==str(i):
        count+=1
print(count)

18696


In [190]:
s="nan"
rep_s="Company has responded to the consumer and the CFPB and chooses not to provide a public response"
rep_s2="Company chooses not to provide a public response"
c=0
for i in ls:
    if s == str(data["Company-response"].iloc[i]):
        c+=1
        if c<=9348: ## half the number of nans
            data["Company-response"].iloc[i]=rep_s
        else:
            data["Company-response"].iloc[i]=rep_s2
            

##  nans replaced for Closed with explanation

In [191]:
data.isnull().sum()

Complaint-ID                     0
Date-received                    0
Transaction-Type                 0
Complaint-reason                 0
Company-response              1947
Date-sent-to-company             0
Complaint-Status                 0
Consumer-disputes             7698
Consumer-complaint-summary       0
dtype: int64

In [192]:
data["Complaint-Status"].unique()

array(['Closed with explanation', 'Closed with non-monetary relief',
       'Closed', 'Closed with monetary relief', 'Untimely response'],
      dtype=object)

In [193]:
ls=[]
count=-1
for i in data["Complaint-Status"]:
    count+=1
    if i == "Closed with monetary relief":
        ls.append(count)

In [194]:
c=0
s="nan"
rep_s="Company has responded to the consumer and the CFPB and chooses not to provide a public response"
for i in ls:
    if s == str(data["Company-response"].iloc[i]):
        c+=1

In [195]:

c=0
s="nan"
rep_s="Company has responded to the consumer and the CFPB and chooses not to provide a public response"
for i in ls:
    if s == str(data["Company-response"].iloc[i]):  ## nans replaced
        data["Company-response"].iloc[i]=rep_s

## nans with monetry relief replaced

In [196]:
ls=[]
count=-1
for i in data["Complaint-Status"]:
    count+=1
    if i == "Closed":
        ls.append(count)

In [197]:
len(ls)

809

In [198]:
c=0
s="nan"
rep_s="Company can't verify or dispute the facts in the complaint"
for i in ls:
    if s == str(data["Company-response"].iloc[i]):  ## nans replaced
        data["Company-response"].iloc[i]=rep_s

## nans with closed replaced

In [199]:
ls=[]
count=-1
for i in data["Complaint-Status"]:
    count+=1
    if i == "Untimely response":
        ls.append(count)

In [200]:
c=0
s="nan"
rep_s="Company believes complaint caused principally by actions of third party outside the control or direction of the companyt"
for i in ls:
    if s == str(data["Company-response"].iloc[i]):  ## nans replaced
        data["Company-response"].iloc[i]=rep_s
        c+=1

## nans with Untimely response

In [201]:
ls=[]
count=-1
for i in data["Consumer-disputes"]:
    count+=1
    if str(i)=="nan":
        ls.append(count)

In [202]:
c=0
s="nan"
rep_s="No"
for i in ls:
    if s == str(data["Consumer-disputes"].iloc[i]):  ## nans replaced
        data["Consumer-disputes"].iloc[i]=rep_s

In [203]:
len(data["Transaction-Type"].unique())

18

In [204]:
#data=pd.get_dummies(data,columns=["Transaction-Type"],drop_first=True)

In [205]:
data=pd.get_dummies(data,columns=["Complaint-reason"],drop_first=True)

In [206]:
data=pd.get_dummies(data,columns=["Company-response"],drop_first=True)

In [207]:
data=pd.get_dummies(data,columns=["Consumer-disputes"],drop_first=True)

In [208]:
data.shape

(43266, 166)

In [209]:
del data["Complaint-ID"]
del data["Date-received"]
del data["Date-sent-to-company"]
del data["Consumer-complaint-summary"]
del data["Transaction-Type"]

In [210]:
data.head()

Complaint-Status  \
0          Closed with explanation   
1  Closed with non-monetary relief   
2          Closed with explanation   
3          Closed with explanation   
4          Closed with explanation   

   Complaint-reason_Account opening, closing, or management  \
0                                                  0          
1                                                  0          
2                                                  0          
3                                                  0          
4                                                  0          

   Complaint-reason_Account terms and changes  Complaint-reason_Adding money  \
0                                           0                              0   
1                                           0                              0   
2                                           0                              0   
3                                           0                              0   
4                                           0                              0   

   Complaint-reason_Advertising  Complaint-reason_Advertising and marketing  \
0                             0                                           0   
1                             0                                           0   
2                             0                                           0   
3                             0                                           0   
4                             0                                           0   

   Complaint-reason_Advertising and marketing, including promotional offers  \
0                                                  0                          
1                                                  0                          
2                                                  0                          
3                                                  0                          
4                                                  0                          

   Complaint-reason_Advertising, marketing or disclosures  \
0                                                  0        
1                                                  0        
2                                                  0        
3                                                  0        
4                                                  0        

   Complaint-reason_Application processing delay  \
0                                              0   
1                                              0   
2                                              0   
3                                              0   
4                                              0   

   Complaint-reason_Application, originator, mortgage broker  \
0                                                  0           
1                                                  0           
2                                                  0           
3                                                  0           
4                                                  0           

           ...            \
0          ...             
1          ...             
2          ...             
3          ...             
4          ...             

   Company-response_Company believes complaint is the result of an isolated error  \
0                                                  0                                
1                                                  0                                
2                                                  0                                
3                                                  0                                
4                                                  0                                

   Company-response_Company believes complaint relates to a discontinued policy or procedure  \
0                                                  0                                           
1                                         

In [211]:
j=-1
ls=[]
for i in data["Complaint-Status"]:
    j+=1
    if i =="Closed with explanation":
        ls.append(j)

In [213]:
data_2=data.copy()
data_2.drop(data_2.index[ls],inplace=True)

In [221]:
y_train=data["Complaint-Status"].copy()
y_train.shape[0]

43266

In [225]:
for i in range(y_train.shape[0]):
    if(y_train.iloc[i]=="Closed with explanation"):
        y_train.iloc[i]=1
    else:
        y_train.iloc[i]=0
        
    

In [230]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_train_2=data_2["Complaint-Status"].copy()
y_train_2=le.fit_transform(y_train_2)

array([2, 2, 2, ..., 1, 0, 2], dtype=int64)

In [233]:
np.unique(y_train_2)

array([0, 1, 2, 3], dtype=int64)

In [234]:
del data_2["Complaint-Status"]
del data["Complaint-Status"]

In [240]:
from sklearn.svm import SVC

In [242]:
from sklearn.metrics import f1_score
clf = SVC(kernel = 'linear', C=10).fit(data, y_train)
print(clf.score(data,y_train))

0.8100355937687792


In [54]:
score = f1_score(y_pred, y_train,average='micro')

In [ ]:
clf2 = SVC(kernel = 'linear', C=10000000).fit(data_2, y_train_2)

In [244]:
print(clf2.score(data_2,y_train_2))

0.806268124024091
